### PR TITLE
Follow a node and give the possibility to see the nodes number

### PR DESCRIPTION
**Pull request by NicolasTHU**

### CODE REVIEW

**Comment by ilyasst** [comment]
@arpcorrea This review is yours ! Please contact @NicolasTHU on the #mudic channel if you have questions about the code or this PR. However, you should be able to install and run the code without Nicolas' help if you rely on the README and documentation.

**Review by arpcorrea — APPROVED** [review]
The code runs pretty well, no errors nor useless output messages.
However, as user, I think that running an own analysis is not trivial. I would suggest improvements on the readme, guiding the user on how properly use it.

**Comment by PolymerGuy** [comment]
Hi! @ilyasst,  @NicolasTHU and @arpcorrea.
Some quick comments. The docstrings should ideally be updated so that is easy to understand what "visualize_node" and  "save_nodes" implies in practice. I would also love to challenge @NicolasTHU to simplify the save_node function so that it does not contain as much duplicate code.

**Review by ilyasst — CHANGES_REQUESTED** [review]
The new update looks good ! However, the code does not run for me, I think that there is a problem with the row/column and node numbers between the quick_start and viz. When I run the quick_start:
```
muDIC.solver.correlate:INFO:Processing frame nr: 85
root:INFO:Converged in 15 iterations
root:INFO:Post processing results from Q4 elements. The seed variable is ignored and the values are extracted at the element centers. Use the upscale value to get interpolated fields.
Traceback (most recent call last):
  File "quick_start.py", line 56, in <module>
    viz.element_history(field="displacement", row=1, column=3, component = (1,1))
  File "/home/buster/Repositories/ets-lipec/muDIC/muDIC/post/viz.py", line 481, in element_history
    plt.plot(list(range(len(self.images))),self.fields.get(field)[0,component[0],row,column,:])
NameError: name 'row' is not defined
```

**Comment by NicolasTHU** [comment]
Yes I made a mistake, indeed, I forget to change the "node=" by "row= , column=" in the viz.element_history() function. The new commit should work well.

**Review by ilyasst — CHANGES_REQUESTED** [review]
In a fresh environment, I got this when I tried running the latest commit in this PR:
```
muDIC.solver.correlate:INFO:Processing frame nr: 9
root:INFO:Converged in 8 iterations
root:INFO:Post processing results from Q4 elements. The seed variable is ignored and the values are extracted at the element centers. Use the upscale value to get interpolated fields.
Traceback (most recent call last):
  File "quick_start.py", line 56, in <module>
    viz.element_history(field="displacement", row=1, column=3, component = (1,1))
  File "/home/buster/Repositories/ets-lipec/muDIC/muDIC/post/viz.py", line 481, in element_history
    plt.plot(list(range(len(self.images))),self.fields.get(field)[0,component[0],row,column,:])
  File "/home/buster/Repositories/ets-lipec/muDIC/.env/lib/python3.8/site-packages/matplotlib/pyplot.py", line 2824, in plot
    return gca().plot(
  File "/home/buster/Repositories/ets-lipec/muDIC/.env/lib/python3.8/site-packages/matplotlib/axes/_axes.py", line 1743, in plot
    lines = [*self._get_lines(*args, data=data, **kwargs)]
  File "/home/buster/Repositories/ets-lipec/muDIC/.env/lib/python3.8/site-packages/matplotlib/axes/_base.py", line 273, in __call__
    yield from self._plot_args(this, kwargs)
  File "/home/buster/Repositories/ets-lipec/muDIC/.env/lib/python3.8/site-packages/matplotlib/axes/_base.py", line 399, in _plot_args
    raise ValueError(f"x and y must have same first dimension, but "
ValueError: x and y must have same first dimension, but have shapes (86,) and (10,)
```

**Review by ilyasst — APPROVED** [review]
All right, it works now :+1:

**Pull request merged**
